[package]
name = "source-list-map-wasm-api"
version = "0.1.0"
authors = ["Jevan Chan <jevan.cnchan@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
source-list-map = { path = ".." }
serde = "1.0.59"
serde_derive = "1.0.59"
serde_json = "1.0.17"
